FROM ubuntu:latest

RUN apt-get update \
	&& apt-get -y install wget \
	&& rm -rf /var/lib/apt/lists/*
	
RUN cd /tmp/ \
	&& wget http://ccb.jhu.edu/software/stringtie/dl/stringtie-1.3.3b.Linux_x86_64.tar.gz \
	&& tar -xzvf stringtie-1.3.3b.Linux_x86_64.tar.gz \
	&& rm -rf stringtie-1.3.3b.Linux_x86_64.tar.gz \
	&& cd stringtie-1.3.3b.Linux_x86_64/ \
	&& mv stringtie /usr/local/bin/

# download jq and make it executable
ENV JQ http://stedolan.github.io/jq/download/linux64/jq 
RUN cd /usr/local/bin && wget --quiet ${JQ} && chmod 700 jq	

RUN cd /usr/local/bin && wget --quiet http://bench.cs.vt.edu/bash-scripts-for-docker/StringTie-bash.sh && chmod 700 StringTie-bash.sh
ENTRYPOINT ["StringTie-bash.sh"]
